# Generated by Django 5.2 on 2025-04-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='nome',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='Outros', max_length=50),
        ),
    ]
