# Generated by Django 5.2 on 2025-04-16 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_transaction_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='categoria',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='descricao',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='tipo',
            new_name='transaction_type',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='valor',
            new_name='value',
        ),
    ]
